{
 "title": "OpenVidu Server Metrics",
 "description": "Dashboard with some relevant metrics exposed by OpenVidu Server",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Active Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(livekit_room_total)", "legendFormat": "active rooms" }
   ]
  },
  {
   "title": "Active Participants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(livekit_participant_total)", "legendFormat": "active participants" }
   ]
  },
  {
   "title": "Published Tracks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(kind) (livekit_track_published_total)",
     "legendFormat": "published {{kind}} tracks"
    }
   ]
  },
  {
   "title": "Subscribed Tracks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(kind) (livekit_track_subscribed_total)",
     "legendFormat": "subscribed {{kind}} tracks"
    }
   ]
  },
  {
   "title": "Packet Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(direction) (rate(livekit_packet_bytes{direction=\"outgoing\"}[$__rate_interval]))",
     "legendFormat": "bytes sent"
    },
    {
     "expr": "sum by(direction) (rate(livekit_packet_bytes{direction=\"incoming\"}[$__rate_interval]))",
     "legendFormat": "bytes received"
    }
   ]
  },
  {
   "title": "Packet Loss Percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(source) (livekit_packet_loss_percent_sum{direction=\"outgoing\"})",
     "legendFormat": "subscribed {{source}}"
    },
    {
     "expr": "sum by(source) (livekit_packet_loss_percent_sum{direction=\"incoming\"})",
     "legendFormat": "published {{source}}"
    }
   ]
  },
  {
   "title": "Quality Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(livekit_quality_score_sum) / sum(livekit_quality_score_count)",
     "legendFormat": "quality score"
    }
   ]
  }
 ]
}