{
 "title": "OpenVidu Logs",
 "description": "Dashboard containing different visualization for logs from OpenVidu services",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {}
   },
   { "name": "room_id" },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "All Containers Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=~\".+\"} |~ `$filter`"
    }
   ]
  },
  {
   "title": "Room Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"openvidu\"} | room_id =~ `$room_id.*` |~ `$filter`"
    }
   ]
  },
  { "title": "Service: $service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "service" },
  {
   "title": "$service Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{container=\"$service\"} |~ `$filter`"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "{container=\"$service\", level=\"warning\"} |~ `$filter`"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "{container=\"$service\", level=\"error\"} |~ `$filter`"
    }
   ]
  }
 ]
}